### ISSUE TITLE
CrocoParallel: handle non-yearly forcings

### ISSUE THREAD

**Issue by bertrandcz** [bertrandcz/CrocO_toolbox#14]
Jari-Pekka would need to load forcings with custom datelimits (not from 0801 to 0801, not single-year)

**Comment by jpnousu** [comment]
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jpnousu/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jpnousu/anaconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 332, in mb_prepare
    self.prepare_offline_env(date, idate, mbdir, mb, mbdirs_forc)
  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 248, in prepare_offline_env
    safe_create_link(self.options.forcing + '/' + mbdirs_forc + '/meteo/FORCING_' + date_begin_forc.strftime('%Y%m%d%H') + '_' + date_end_forc.strftime('%Y%m%d%H') + '.nc',
  File "/home/jpnousu/CrocO_toolbox/utilcrocO.py", line 692, in safe_create_link
    raise Exception('safe_create_link: {0} does not exist'.format(src))
Exception: safe_create_link: /home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/CrocO_vortex_sandbox/safran/siikaneva1/forcing_siikaneva1/mb0001//meteo/FORCING_2018080106_2019080106.nc does not exist
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/notebooks/run_local_ESCROC_example.py", line 42, in <module>
    run = CrocoParallel(options)

  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 49, in __init__
    self.setup()

  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 104, in setup
    self.escrocs = OfflinePools(self.options)

  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 216, in __init__
    self.setup()

  File "/home/jpnousu/CrocO_toolbox/CrocoParallel.py", line 228, in setup
    p.map(self.mb_prepare, [[date, idate, mbdir, mb, mbdirs_forc] for idate, date in enumerate(self.options.stopdates)

  File "/home/jpnousu/anaconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "/home/jpnousu/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value

Exception: safe_create_link: /home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/CrocO_vortex_sandbox/safran/siikaneva1/forcing_siikaneva1/mb0001//meteo/FORCING_2018080106_2019080106.nc does not exist

**Comment by jpnousu** [comment]
It was not 'IOError' so I had to remove that from the 'except'

**Comment by bertrandcz** [comment]
Sorry, I forgot to commit changes to `utilcrocO.py`
