### ISSUE TITLE
Problem launching ensemble run with only one point 

### ISSUE THREAD

**Issue by jpnousu** [bertrandcz/CrocO_toolbox#15]
runfile('/home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/notebooks/run_local_ESCROC_example.py', wdir='/home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/notebooks')
Traceback (most recent call last):

  File "/home/jpnousu/CROSIM/RESULTS/ENSEMBLE_test/SIIKANEVA/notebooks/run_local_ESCROC_example.py", line 41, in <module>
    options = set_options(args,pathConf=os.environ['VORTEXPATH'] + conffile, useVortex = False)

  File "/home/jpnousu/CrocO_toolbox/crocO.py", line 267, in set_options
    options = parse_classes(options)

  File "/home/jpnousu/CrocO_toolbox/utilcrocO.py", line 55, in parse_classes
    options.classes_e = sorted(np.unique(list(map(str, map(int, options.pgd.elev)))))

TypeError: iteration over a 0-d array

**Comment by jpnousu** [comment]
![image](https://user-images.githubusercontent.com/69629412/167094248-49341ce8-9a1f-4949-b27e-826c3a98b46c.png)
