### ISSUE TITLE
Indefinite waiting time for thread creation 

### ISSUE THREAD

**Issue by capetienne** [bertrandcz/CrocO_toolbox#23]
Running the sandbox (ol or global) takes a huge amount of time (3-4h ) even with only one small obs.  The problem is located in Crocoparrallel. it seems to stay in waiting position until timeout : 
`cape@px08380:~/sandbox$ python3 run_sandbox.py
setup duration: [0.45673561096191406](callto:0.45673561096191406)
|         soda: [0.28180837631225586](callto:0.28180837631225586)
|       escroc: [0.1749260425567627](callto:0.1749260425567627)
ESCROC simulation until [2014011106](callto:2014011106):   0%|                                                                                                                                            | 0/2 [00:00<?, ?it/s]number of cores used: 3
ESCROC simulation until [2014011106](callto:2014011106):   0%|                                                                                                                                            | 0/2 [06:43<?, ?it/s]
Traceback (most recent call last):

  File "run_sandbox.py", line 45, in <module>
    run.run(cleanup=False)
  File "/home/cape/git/CrocO_toolbox/CrocoParallel.py", line 121, in run
    self.escrocs.run(dd)
  File "/home/cape/git/CrocO_toolbox/CrocoParallel.py", line 325, in run
    p.map(self.mb_run, [['/'.join([self.xpiddir, date, mbdir])] for mbdir in self.mbdirs])
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
Process ForkPoolWorker-9:
Process ForkPoolWorker-7:
Process ForkPoolWorker-8:
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 762, in wait

    self._event.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt`

![Capture d’écran de 2022-06-13 16-59-47](https://user-images.githubusercontent.com/76118668/174261791-5b800b01-962a-4433-a3f0-030466bb9d74.png)
![Capture d’écran de 2022-06-13 15-29-10](https://user-images.githubusercontent.com/76118668/174261918-9854866d-20c1-4dc5-84a2-b8e4cb536294.png)

python version : 3.8.10 

version surfex :  branche cen

**Comment by bertrandcz** [comment]
Hi Etienne, thanks for this detailed issue. How many members are you running?

**Comment by bertrandcz** [comment]
@jpnousu, does this problem ring a bell/look similar to yours?

**Comment by MathieuCen** [comment]
Hi,

I think this is coming from a change in Python configuration: there were some changes in Multiprocessing between Python3.7 (and previous) and Python3.8

Etienne is working on Python3.8 and (I believe) that's why this bug occurs.
I've started to check what are the differences via Stackoverflow (you can have a look on the links below) but hopefully Etienne succed in solving his problem before I take this time.

mathieu
PS: the links
https://stackoverflow.com/questions/65098398/why-using-fork-works-but-using-spawn-fails-in-python3-8-multiprocessing
https://stackoverflow.com/questions/63554398/python3-8-multiprocess-lock
https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/
https://stackoverflow.com/questions/63747605/python-3-8-breaks-python-3-5-code-using-multiprocessing-and-globals

**Comment by bertrandcz** [comment]
ah nice, well spotted @MathieuCen, thanks! I will investigate this on Monday.

**Comment by bertrandcz** [comment]
I cannot reproduce the bug, but I think that @MathieuCen was spot on.
It seems that this bug was fixed in python 3.8.13. Could you try to upgrade to this version and let me know if you still have the bug?
